package hendrix.projectEuler.problem1_15;

/**
 * Description:
 * Problem02, Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem02 {
    /*
    Solution description here
    */
    private static String solve() {
        //TODO
        return "Answer Here";
    }

    public static void main(String[] args) {
        long startTime = System.nanoTime();
        String result = solve();
        long endTime = System.nanoTime();
        System.out.println("Answer: " + result + "\nProcess took " + (endTime - startTime) / 1000 + "ms to execute");
    }
}
/*
Put result here
*/